### ISSUE TITLE
更新 v0.3.2 后搜索图标依然错位

### ISSUE THREAD

**Issue by LiarrDev** [lmm214/gridea-theme-breek#11]
如图：

![搜索图标错位](https://user-images.githubusercontent.com/40908569/79638402-98285600-81b7-11ea-9cf1-960598301e71.png)

但是我看到您的网站搜索图标是没有错位的，不知道问题出在哪里 😥

**Comment by LiarrDev** [comment]
我改回上一个版本的代码后位置变回居中：

```CSS
form.search-form .submit {
  position: absolute;
  right: 20px;
  top: 50%;
  color: #fff;
  background: none;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  margin-top: -8px;
  font-size: 22px;
}
```
